### ISSUE TITLE
Use Zig's package manager instead of gitmodules

### ISSUE THREAD

**Issue by Ev1lT3rm1nal** [chadwain/rem#10]
Add `build.zig.zon` instead of `.gitmodules`

**Comment by ThePuzzledDev** [comment]
Has anyone decided to actually do this?

**Comment by ThePuzzledDev** [comment]
I have no plans to maintain this, but here's a fork that might work for now. https://github.com/ThePuzzledDev/rem/tree/master

**Comment by Ev1lT3rm1nal** [comment]
> but here's a fork that might work for now
Make a PR

**Comment by ThePuzzledDev** [comment]
I'm not exactly sure of how quality it is, so I didn't want to suggest it as I literally got the minimum stuff to get it working. I got rid of all the tests and examples because they weren't working with my Zig version.

**Comment by Ev1lT3rm1nal** [comment]
OMG this is great hahaha

**Comment by chadwain** [comment]
@ThePuzzledDev Feel free to make a pull request to add support for the package manager. :)  But don't remove gitmodules, as I'd like to support both options for now.

As for the broken tests, I have an open PR in zig that _should_ fix them (https://github.com/ziglang/zig/pull/18674), so leave those in as well.
